// Package compiler 提供 .gox 文件编译功能
package compiler

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/ayanmw/go-react-ink/internal/codegen"
	"github.com/ayanmw/go-react-ink/internal/lexer"
	"github.com/ayanmw/go-react-ink/internal/parser"
	"github.com/ayanmw/go-react-ink/internal/scanner"
)

// Compiler 编译器
type Compiler struct {
	ComponentPkg       string // 组件包名 (如 "ink")
	removeClosingParen bool   // 内部状态：是否需要移除闭合括号
}

// New 创建新的编译器
func New(componentPkg string) *Compiler {
	return &Compiler{
		ComponentPkg: componentPkg,
	}
}

// CompileFile 编译单个 .gox 文件
func (c *Compiler) CompileFile(inputPath string) ([]byte, error) {
	content, err := os.ReadFile(inputPath)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	return c.Compile(inputPath, string(content))
}

// Compile 编译源代码
func (c *Compiler) Compile(filename string, source string) ([]byte, error) {
	// 1. 扫描 JSX 区域
	s := scanner.New(source)
	segments, err := s.Scan()
	if err != nil {
		return nil, fmt.Errorf("scan: %w", err)
	}

	// 2. 生成输出代码
	var output bytes.Buffer
	output.WriteString("// Code generated by go-ink compiler. DO NOT EDIT.\n")
	output.WriteString("// Source: " + filename + "\n\n")

	// 处理每个段
	for i, seg := range segments {
		switch seg.Type {
		case scanner.SegmentGoCode:
			// Go 代码直接输出
			content := seg.Content

			// 如果下一个段是 JSX 且当前段以 return ( 结尾，需要处理
			if i+1 < len(segments) && segments[i+1].Type == scanner.SegmentJSX {
				trimmed := strings.TrimSpace(content)
				if strings.HasSuffix(trimmed, "return (") {
					// 移除末尾的 ( 和空白
					content = strings.TrimRight(content, " \t\n\r")
					content = strings.TrimSuffix(content, "(")
					// 标记需要特殊处理
					c.removeClosingParen = true
				}
			}

			// 如果前面处理了 return (，需要移除后续的 )
			if c.removeClosingParen && i > 0 && segments[i-1].Type == scanner.SegmentJSX {
				// 移除开头的 ) 和空白
				content = strings.TrimLeft(content, " \t\n\r")
				if strings.HasPrefix(content, ")") {
					content = content[1:]
				}
				c.removeClosingParen = false
			}

			output.WriteString(content)

		case scanner.SegmentJSX:
			// JSX 需要编译
			var jsxCode string
			if c.removeClosingParen {
				// 前面已经有 return，只生成元素代码（不生成 return）
				jsxCode = c.compileJSXNoReturn(seg.Content)
			} else {
				jsxCode = c.compileJSX(seg.Content)
			}
			output.WriteString(jsxCode)
		}
	}

	// 确保导入正确
	outputBytes := output.Bytes()
	outputBytes = c.fixImports(outputBytes)

	return outputBytes, nil
}

// compileJSX 编译 JSX 代码
func (c *Compiler) compileJSX(source string) string {
	// 词法分析
	l := lexer.New(source)
	tokens := l.Lex()

	// 语法分析
	p := parser.New(tokens)
	node, err := p.Parse()
	if err != nil {
		// 解析失败，返回原始代码并添加注释
		return fmt.Sprintf("/* PARSE ERROR: %v */\n%s", err, source)
	}

	// 转换 AST 为 codegen Node
	cgNode := c.convertAST(node)

	// 生成代码
	return codegen.GenerateReturn(cgNode, c.ComponentPkg)
}

// compileJSXNoReturn 编译 JSX 代码（不添加 return）
func (c *Compiler) compileJSXNoReturn(source string) string {
	// 词法分析
	l := lexer.New(source)
	tokens := l.Lex()

	// 语法分析
	p := parser.New(tokens)
	node, err := p.Parse()
	if err != nil {
		// 解析失败，返回原始代码并添加注释
		return fmt.Sprintf("/* PARSE ERROR: %v */\n%s", err, source)
	}

	// 转换 AST 为 codegen Node
	cgNode := c.convertAST(node)

	// 生成代码（不包含 return）
	gen := codegen.New(c.ComponentPkg)
	return gen.GenerateNode(cgNode)
}

// convertAST 转换 parser AST 为 codegen AST
func (c *Compiler) convertAST(node parser.Node) codegen.Node {
	cgNode := codegen.Node{
		Type:       codegen.NodeType(node.Type),
		TagName:    node.TagName,
		Attributes: make(map[string]codegen.AttrValue),
		Children:   make([]codegen.Node, 0),
		Value:      node.Value,
		Spread:     node.Spread,
	}

	// 转换属性
	for k, v := range node.Attributes {
		cgNode.Attributes[k] = codegen.AttrValue{
			IsExpression: v.IsExpression,
			Value:        v.Value,
		}
	}

	// 转换子节点
	for _, child := range node.Children {
		cgNode.Children = append(cgNode.Children, c.convertAST(child))
	}

	return cgNode
}

// fixImports 修正导入
func (c *Compiler) fixImports(source []byte) []byte {
	content := string(source)

	// 检查是否需要导入
	needsCore := strings.Contains(content, "core.")
	needsInk := strings.Contains(content, c.ComponentPkg+".")

	// 如果没有使用 CreateElement 等，不需要添加导入
	if !needsCore && !needsInk {
		return source
	}

	// 找到 package 声明位置
	pkgIndex := strings.Index(content, "package ")
	if pkgIndex == -1 {
		// 没有 package 声明，在开头添加
		importBlock := buildImportBlock(needsCore, needsInk, c.ComponentPkg)
		newContent := fmt.Sprintf("package main\n\nimport (\n%s)\n\n%s", importBlock, content)
		return []byte(newContent)
	}

	// 找到 package 声明结束位置
	pkgEnd := strings.Index(content[pkgIndex:], "\n")
	if pkgEnd == -1 {
		pkgEnd = len(content) - pkgIndex
	}

	// 在 package 声明后插入 import
	before := content[:pkgIndex+pkgEnd+1]
	after := content[pkgIndex+pkgEnd+1:]

		// 检查是否已有 import 声明
	if strings.Contains(after, "import ") {
		// 已有 import，需要智能合并
		importStart := strings.Index(after, "import (")
		if importStart != -1 {
			importEnd := strings.Index(after[importStart:], ")")
			if importEnd != -1 {
				importEnd += importStart
				existingImports := after[importStart : importEnd+1]

				// 解析已有导入并添加缺失的，同时修正别名
				newImportBlock := mergeImports(existingImports, needsCore, needsInk, c.ComponentPkg)
				newContent := before + after[:importStart] + newImportBlock + after[importEnd+1:]
				return []byte(newContent)
			}
		}
		// 单行 import
		singleImportStart := strings.Index(after, "import \"")
		if singleImportStart != -1 {
			importEnd := strings.Index(after[singleImportStart:], "\n")
			if importEnd != -1 {
				importEnd += singleImportStart
				importBlock := buildImportBlock(needsCore, needsInk, c.ComponentPkg)
				newContent := before + after[:singleImportStart] +
					fmt.Sprintf("import (\n%s%s)\n", importBlock, after[singleImportStart:importEnd+1]) +
					after[importEnd+1:]
				return []byte(newContent)
			}
		}
		return source
	}

	// 没有 import，添加新的 import 块
	importBlock := buildImportBlock(needsCore, needsInk, c.ComponentPkg)
	newContent := before + fmt.Sprintf("\nimport (\n%s)\n\n", importBlock) + after
	return []byte(newContent)
}

// buildImportBlock 构建导入块内容
func buildImportBlock(needsCore, needsInk bool, componentPkg string) string {
	var block string
	if needsCore {
		block += "\t\"github.com/ayanmw/go-react-ink/pkg/core\"\n"
	}
	if needsInk {
		block += fmt.Sprintf("\t%s \"github.com/ayanmw/go-react-ink/pkg/components\"\n", componentPkg)
	}
	return block
}

// mergeImports 合并导入，替换已有导入为正确的别名导入
func mergeImports(existing string, needsCore, needsInk bool, componentPkg string) string {
	lines := strings.Split(existing, "\n")
	var newLines []string

	// 记录已添加的导入
	addedCore := false
	addedInk := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// 跳过 import ( 和 )
		if trimmed == "import (" || trimmed == ")" || trimmed == "" {
			if trimmed == ")" {
				// 在关闭括号前添加缺失的导入
				if needsCore && !addedCore {
					newLines = append(newLines, "\t\"github.com/ayanmw/go-react-ink/pkg/core\"")
				}
				if needsInk && !addedInk {
					newLines = append(newLines, fmt.Sprintf("\t%s \"github.com/ayanmw/go-react-ink/pkg/components\"", componentPkg))
				}
			}
			newLines = append(newLines, line)
			continue
		}

		// 检查是否是 core 导入
		if strings.Contains(line, "github.com/ayanmw/go-react-ink/pkg/core") {
			if needsCore {
				newLines = append(newLines, "\t\"github.com/ayanmw/go-react-ink/pkg/core\"")
				addedCore = true
			}
			continue
		}

		// 检查是否是 components 导入
		if strings.Contains(line, "github.com/ayanmw/go-react-ink/pkg/components") {
			if needsInk {
				// 替换为别名导入
				newLines = append(newLines, fmt.Sprintf("\t%s \"github.com/ayanmw/go-react-ink/pkg/components\"", componentPkg))
				addedInk = true
			}
			continue
		}

		// 保留其他导入
		newLines = append(newLines, line)
	}

	return strings.Join(newLines, "\n")
}

// CompileDir 编译目录
func (c *Compiler) CompileDir(inputDir string, outputDir string) error {
	// 遍历目录
	entries, err := os.ReadDir(inputDir)
	if err != nil {
		return fmt.Errorf("read dir: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			// 递归处理子目录
			subInput := filepath.Join(inputDir, entry.Name())
			subOutput := filepath.Join(outputDir, entry.Name())
			if err := c.CompileDir(subInput, subOutput); err != nil {
				return err
			}
			continue
		}

		// 只处理 .gox 文件
		if !strings.HasSuffix(entry.Name(), ".gox") {
			continue
		}

		inputPath := filepath.Join(inputDir, entry.Name())
		outputPath := filepath.Join(outputDir, entry.Name()[:len(entry.Name())-4] + ".go") // .gox -> .go

		// 编译文件
		output, err := c.CompileFile(inputPath)
		if err != nil {
			return fmt.Errorf("compile %s: %w", inputPath, err)
		}

		// 写入输出
		if err := os.WriteFile(outputPath, output, 0644); err != nil {
			return fmt.Errorf("write %s: %w", outputPath, err)
		}
	}

	return nil
}

// Result 编译结果
type Result struct {
	InputPath  string
	OutputPath string
	Output     []byte
	Error      error
}

// CompileFiles 编译多个文件
func (c *Compiler) CompileFiles(inputs []string, stdout io.Writer) error {
	for _, input := range inputs {
		output, err := c.CompileFile(input)
		if err != nil {
			fmt.Fprintf(stdout, "// ERROR: %s: %v\n", input, err)
			continue
		}

		if stdout != nil {
			fmt.Fprintf(stdout, "// Source: %s\n", input)
			stdout.Write(output)
			fmt.Fprintln(stdout)
		}
	}

	return nil
}
