// Package compiler 提供 .gox 文件编译功能
package compiler

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/ayanmw/go-react-ink/internal/codegen"
	"github.com/ayanmw/go-react-ink/internal/lexer"
	"github.com/ayanmw/go-react-ink/internal/parser"
	"github.com/ayanmw/go-react-ink/internal/scanner"
)

// Compiler 编译器
type Compiler struct {
	ComponentPkg string // 组件包名 (如 "ink")
}

// New 创建新的编译器
func New(componentPkg string) *Compiler {
	return &Compiler{
		ComponentPkg: componentPkg,
	}
}

// CompileFile 编译单个 .gox 文件
func (c *Compiler) CompileFile(inputPath string) ([]byte, error) {
	content, err := os.ReadFile(inputPath)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	return c.Compile(inputPath, string(content))
}

// Compile 编译源代码
func (c *Compiler) Compile(filename string, source string) ([]byte, error) {
	// 1. 扫描 JSX 区域
	s := scanner.New(source)
	segments, err := s.Scan()
	if err != nil {
		return nil, fmt.Errorf("scan: %w", err)
	}

	// 2. 生成输出代码
	var output bytes.Buffer
	output.WriteString("// Code generated by go-ink compiler. DO NOT EDIT.\n")
	output.WriteString("// Source: " + filename + "\n\n")

	// 处理每个段
	for i, seg := range segments {
		switch seg.Type {
		case scanner.SegmentGoCode:
			// Go 代码直接输出
			output.WriteString(seg.Content)

		case scanner.SegmentJSX:
			// JSX 需要编译
			jsxCode := c.compileJSX(seg.Content)
			output.WriteString(jsxCode)
		}

		// 添加换行保持分隔
		if i < len(segments)-1 && !strings.HasSuffix(seg.Content, "\n") {
			output.WriteString("\n")
		}
	}

	// 确保导入正确
	outputBytes := output.Bytes()
	outputBytes = c.fixImports(outputBytes)

	return outputBytes, nil
}

// compileJSX 编译 JSX 代码
func (c *Compiler) compileJSX(source string) string {
	// 词法分析
	l := lexer.New(source)
	tokens := l.Lex()

	// 语法分析
	p := parser.New(tokens)
	node, err := p.Parse()
	if err != nil {
		// 解析失败，返回原始代码并添加注释
		return fmt.Sprintf("/* PARSE ERROR: %v */\n%s", err, source)
	}

	// 转换 AST 为 codegen Node
	cgNode := c.convertAST(node)

	// 生成代码
	return codegen.GenerateReturn(cgNode, c.ComponentPkg)
}

// convertAST 转换 parser AST 为 codegen AST
func (c *Compiler) convertAST(node parser.Node) codegen.Node {
	cgNode := codegen.Node{
		Type:       codegen.NodeType(node.Type),
		TagName:    node.TagName,
		Attributes: make(map[string]codegen.AttrValue),
		Children:   make([]codegen.Node, 0),
		Value:      node.Value,
		Spread:     node.Spread,
	}

	// 转换属性
	for k, v := range node.Attributes {
		cgNode.Attributes[k] = codegen.AttrValue{
			IsExpression: v.IsExpression,
			Value:        v.Value,
		}
	}

	// 转换子节点
	for _, child := range node.Children {
		cgNode.Children = append(cgNode.Children, c.convertAST(child))
	}

	return cgNode
}

// fixImports 修正导入
func (c *Compiler) fixImports(source []byte) []byte {
	content := string(source)

	// 检查是否需要导入
	needsCore := strings.Contains(content, "core.")
	needsInk := strings.Contains(content, c.ComponentPkg+".")

	// 如果没有使用 CreateElement 等，不需要添加导入
	if !needsCore && !needsInk {
		return source
	}

	// 检查是否已有 import 块
	importBlock := ""
	if needsCore {
		importBlock += fmt.Sprintf("\t\"github.com/ayanmw/go-react-ink/pkg/core\"\n")
	}
	if needsInk {
		importBlock += fmt.Sprintf("\t\"github.com/ayanmw/go-react-ink/pkg/components/%s\"\n", c.ComponentPkg)
	}

	// 找到 package 声明位置
	pkgIndex := strings.Index(content, "package ")
	if pkgIndex == -1 {
		// 没有 package 声明，在开头添加
		newContent := fmt.Sprintf("package main\n\nimport (\n%s)\n\n%s", importBlock, content)
		return []byte(newContent)
	}

	// 找到 package 声明结束位置
	pkgEnd := strings.Index(content[pkgIndex:], "\n")
	if pkgEnd == -1 {
		pkgEnd = len(content) - pkgIndex
	}

	// 在 package 声明后插入 import
	before := content[:pkgIndex+pkgEnd+1]
	after := content[pkgIndex+pkgEnd+1:]

	// 检查是否已有 import 声明
	if strings.Contains(after, "import ") {
		// 已有 import，在其中添加
		importStart := strings.Index(after, "import (")
		if importStart != -1 {
			importEnd := strings.Index(after[importStart:], ")")
			if importEnd != -1 {
				importEnd += importStart
				existingImports := after[importStart : importEnd+1]
				newImports := existingImports[:len(existingImports)-1] + importBlock + ")"
				newContent := before + after[:importStart] + newImports + after[importEnd+1:]
				return []byte(newContent)
			}
		}
		// 单行 import
		importStart = strings.Index(after, "import \"")
		if importStart != -1 {
			importEnd := strings.Index(after[importStart:], "\n")
			if importEnd != -1 {
				importEnd += importStart
				newContent := before + after[:importStart] +
					fmt.Sprintf("import (\n%s%s)\n", importBlock, after[importStart:importEnd+1]) +
					after[importEnd+1:]
				return []byte(newContent)
			}
		}
		return source
	}

	// 没有 import，添加新的 import 块
	newContent := before + fmt.Sprintf("\nimport (\n%s)\n\n", importBlock) + after
	return []byte(newContent)
}

// CompileDir 编译目录
func (c *Compiler) CompileDir(inputDir string, outputDir string) error {
	// 遍历目录
	entries, err := os.ReadDir(inputDir)
	if err != nil {
		return fmt.Errorf("read dir: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			// 递归处理子目录
			subInput := filepath.Join(inputDir, entry.Name())
			subOutput := filepath.Join(outputDir, entry.Name())
			if err := c.CompileDir(subInput, subOutput); err != nil {
				return err
			}
			continue
		}

		// 只处理 .gox 文件
		if !strings.HasSuffix(entry.Name(), ".gox") {
			continue
		}

		inputPath := filepath.Join(inputDir, entry.Name())
		outputPath := filepath.Join(outputDir, entry.Name()[:len(entry.Name())-1]) // .gox -> .go

		// 编译文件
		output, err := c.CompileFile(inputPath)
		if err != nil {
			return fmt.Errorf("compile %s: %w", inputPath, err)
		}

		// 写入输出
		if err := os.WriteFile(outputPath, output, 0644); err != nil {
			return fmt.Errorf("write %s: %w", outputPath, err)
		}
	}

	return nil
}

// Result 编译结果
type Result struct {
	InputPath  string
	OutputPath string
	Output     []byte
	Error      error
}

// CompileFiles 编译多个文件
func (c *Compiler) CompileFiles(inputs []string, stdout io.Writer) error {
	for _, input := range inputs {
		output, err := c.CompileFile(input)
		if err != nil {
			fmt.Fprintf(stdout, "// ERROR: %s: %v\n", input, err)
			continue
		}

		if stdout != nil {
			fmt.Fprintf(stdout, "// Source: %s\n", input)
			stdout.Write(output)
			fmt.Fprintln(stdout)
		}
	}

	return nil
}
